// build-articles.ts — Sprint 13 task 4 / task 12.
//
// Reads every MDX article from apps/mobile/src/learn/articles/, parses
// frontmatter and body, runs the markdown subset parser, asserts body
// <Source> blocks match frontmatter sources, and emits a typed
// CompiledArticle[] to apps/mobile/src/learn/articleIndex.gen.ts.
//
// Run via `npm run build:articles` from apps/mobile/. The generated
// file IS committed — it's the source of truth the runtime imports.
// CI runs this script and asserts no diff (drift detection).
//
// Design notes:
//   - The runtime never sees raw MDX or YAML. It imports the typed
//     index and walks each article's AST through <ArticleRenderer>.
//   - Voice-lint runs INSIDE the build to catch HARD hits before
//     emitting; soft hits surface as console.warn but don't fail the
//     build.
//   - Source ordering is preserved — articles are sorted by id so the
//     generated file is stable across runs (no spurious diffs).

import * as fs from 'node:fs';
import * as path from 'node:path';
import { parseArticle } from '../src/services/learn/parser';
import { parseMarkdown } from '../src/services/learn/markdown';
import { lintVoiceText, formatVoiceHits } from '../src/services/voice/voiceLint';
import type { CompiledArticle } from '../src/services/learn/ast';

const ROOT = path.resolve(__dirname, '..');
const ARTICLES_DIR = path.join(ROOT, 'src', 'learn', 'articles');
const OUTPUT_FILE = path.join(ROOT, 'src', 'learn', 'articleIndex.gen.ts');

interface BuildResult {
  compiled: CompiledArticle[];
  errors: string[];
  warnings: string[];
}

function build(): BuildResult {
  const errors: string[] = [];
  const warnings: string[] = [];

  if (!fs.existsSync(ARTICLES_DIR)) {
    return {
      compiled: [],
      errors: [`articles dir does not exist: ${ARTICLES_DIR}`],
      warnings,
    };
  }

  const files = fs
    .readdirSync(ARTICLES_DIR)
    .filter(f => f.endsWith('.mdx'))
    .sort();

  const compiled: CompiledArticle[] = [];

  for (const file of files) {
    const fullPath = path.join(ARTICLES_DIR, file);
    const sourcePath = `apps/mobile/src/learn/articles/${file}`;
    const raw = fs.readFileSync(fullPath, 'utf8');

    // Voice-lint the entire file — frontmatter is stripped by the
    // engine, so only body content gets scanned.
    const lintResult = lintVoiceText(raw);
    if (lintResult.hardHits.length > 0) {
      errors.push(
        `[voice-lint HARD] ${sourcePath}\n${formatVoiceHits(lintResult.hardHits)}`,
      );
      continue;
    }
    if (lintResult.softHits.length > 0) {
      warnings.push(
        `[voice-lint soft] ${sourcePath}\n${formatVoiceHits(lintResult.softHits)}`,
      );
    }

    let parsed: ReturnType<typeof parseArticle>;
    try {
      parsed = parseArticle(raw, sourcePath);
    } catch (err) {
      errors.push(`[parse] ${(err as Error).message}`);
      continue;
    }

    const md = parseMarkdown(parsed.body);

    // Reconcile body <Source> blocks against frontmatter sources.
    const fmSources = new Set(parsed.frontmatter.sources);
    const bodySet = new Set(md.bodySources);
    const missingFromBody = [...fmSources].filter(s => !bodySet.has(s));
    const missingFromFrontmatter = [...bodySet].filter(s => !fmSources.has(s));
    if (missingFromBody.length > 0 || missingFromFrontmatter.length > 0) {
      errors.push(
        `[sources mismatch] ${sourcePath}\n` +
          (missingFromBody.length
            ? `  missing from body: ${missingFromBody.join('; ')}\n`
            : '') +
          (missingFromFrontmatter.length
            ? `  missing from frontmatter: ${missingFromFrontmatter.join('; ')}\n`
            : ''),
      );
    }

    compiled.push({
      frontmatter: parsed.frontmatter,
      blocks: md.blocks,
      sourcePath,
    });
  }

  return { compiled, errors, warnings };
}

function emit(compiled: CompiledArticle[]): string {
  const articlesLiteral = JSON.stringify(compiled, null, 2);
  return `// articleIndex.gen.ts — generated by scripts/build-articles.ts
//
// DO NOT EDIT BY HAND. Run \`npm run build:articles\` after changing
// any MDX in src/learn/articles/. CI fails if this file is stale.

import type { CompiledArticle } from '../services/learn/ast';

export const ARTICLES: readonly CompiledArticle[] = ${articlesLiteral} as const;

export const ARTICLES_BY_ID: Readonly<Record<string, CompiledArticle>> =
  ARTICLES.reduce<Record<string, CompiledArticle>>((acc, a) => {
    acc[a.frontmatter.id] = a;
    return acc;
  }, {});
`;
}

function main(): void {
  const result = build();

  for (const w of result.warnings) {
    // eslint-disable-next-line no-console
    console.warn(w);
  }

  if (result.errors.length > 0) {
    // eslint-disable-next-line no-console
    console.error('\nBuild failed:\n');
    for (const e of result.errors) {
      // eslint-disable-next-line no-console
      console.error(e);
      // eslint-disable-next-line no-console
      console.error('');
    }
    process.exit(1);
  }

  const out = emit(result.compiled);
  fs.writeFileSync(OUTPUT_FILE, out, 'utf8');

  // eslint-disable-next-line no-console
  console.log(
    `Wrote ${OUTPUT_FILE} — ${result.compiled.length} article(s), ${result.warnings.length} soft warning(s).`,
  );
}

main();
