// articleIndex.gen.ts — generated by scripts/build-articles.ts
//
// DO NOT EDIT BY HAND. Run `npm run build:articles` after changing
// any MDX in src/learn/articles/. CI fails if this file is stale.

import type { CompiledArticle } from '../services/learn/ast';

export const ARTICLES: readonly CompiledArticle[] = [
  {
    "frontmatter": {
      "id": "activity-001",
      "title": "Why steps matter for blood pressure",
      "category": "ACTIVITY",
      "audience": [
        "self_buyer",
        "caregiver"
      ],
      "mode_relevance": [
        "self",
        "caregiver",
        "hybrid"
      ],
      "reading_context": {
        "systolic_min": 0,
        "systolic_max": 999,
        "diastolic_min": 0,
        "diastolic_max": 999
      },
      "inline_explainer_priority": 1,
      "related_cards": [
        "activity-002",
        "corr-002"
      ],
      "sources": [
        "JAMA Internal Medicine — step count and cardiovascular outcomes",
        "ACSM Physical Activity Guidelines",
        "Cochrane review — physical activity and blood pressure"
      ],
      "last_reviewed": "2026-05-09",
      "reviewed_by": null,
      "clinical_review_required": false,
      "clinical_reviewed_at": null,
      "locale_status": {
        "en": "complete",
        "yo": "pending",
        "ig": "pending",
        "ha": "pending"
      }
    },
    "blocks": [
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "Of the everyday changes a person can make, regular movement has the strongest research evidence behind it. People who add consistent moderate movement to their week often see their resting numbers settle into a lower range over weeks."
          }
        ]
      },
      {
        "type": "heading",
        "depth": 2,
        "children": [
          {
            "type": "text",
            "value": "What the research has found"
          }
        ]
      },
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "A 2022 review across more than thirty studies found that adults who added consistent moderate movement to their week saw average drops in resting systolic blood pressure of about five to eight mmHg over eight to twelve weeks. The biggest gains came from people moving from very little (under three thousand steps a day) to moderate (six to eight thousand a day). Past about nine or ten thousand steps a day, the additional benefit flattened."
          }
        ]
      },
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "The change is not instant. It builds up across weeks, the way fitness does, and it fades within weeks of stopping."
          }
        ]
      },
      {
        "type": "heading",
        "depth": 2,
        "children": [
          {
            "type": "text",
            "value": "A note on ten thousand steps"
          }
        ]
      },
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "The number ten thousand has a marketing origin, not a clinical one. It came from a Japanese pedometer campaign in the 1960s — the kanji character for ten thousand looked a little like a person walking. Several large studies since then suggest that, for older adults, most of the benefit shows up between seven and nine thousand steps a day, with diminishing returns above that."
          }
        ]
      },
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "The right number for you depends on where you are starting from. Going from two thousand to four thousand steps a day is a more meaningful change than going from nine to eleven thousand."
          }
        ]
      },
      {
        "type": "heading",
        "depth": 2,
        "children": [
          {
            "type": "text",
            "value": "What you may see in your readings"
          }
        ]
      },
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "After a few weeks of consistent walking, many people notice their morning numbers settling into a slightly lower range. The change is gradual; the trend chart is the place to look, not any one morning."
          }
        ]
      },
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "A few things help the habit stick:"
          }
        ]
      },
      {
        "type": "list",
        "ordered": false,
        "items": [
          [
            {
              "type": "text",
              "value": "A short walk after dinner is one of the most studied patterns"
            }
          ],
          [
            {
              "type": "text",
              "value": "Rest days are part of consistency, not a break from it"
            }
          ],
          [
            {
              "type": "text",
              "value": "Pairing the walk with a set time of day matters more than the distance"
            }
          ]
        ]
      },
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "Talk to your doctor about what is right for you."
          }
        ]
      }
    ],
    "sourcePath": "apps/mobile/src/learn/articles/activity-001.mdx"
  },
  {
    "frontmatter": {
      "id": "hr-001",
      "title": "What is resting heart rate?",
      "category": "HR",
      "audience": [
        "self_buyer",
        "caregiver"
      ],
      "mode_relevance": [
        "self",
        "caregiver",
        "hybrid"
      ],
      "reading_context": {
        "systolic_min": 0,
        "systolic_max": 999,
        "diastolic_min": 0,
        "diastolic_max": 999
      },
      "inline_explainer_priority": 1,
      "related_cards": [
        "hr-002",
        "hr-003"
      ],
      "sources": [
        "AHA Scientific Statement on Heart Rate",
        "ACC Resting Heart Rate Reference Values"
      ],
      "last_reviewed": "2026-05-09",
      "reviewed_by": null,
      "clinical_review_required": true,
      "clinical_reviewed_at": null,
      "locale_status": {
        "en": "complete",
        "yo": "pending",
        "ig": "pending",
        "ha": "pending"
      }
    },
    "blocks": [
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "Resting heart rate is how many times your heart beats in a minute when you are sitting still and not under stress. Most healthy adults sit somewhere between 60 and 100 beats per minute."
          }
        ]
      },
      {
        "type": "heading",
        "depth": 2,
        "children": [
          {
            "type": "text",
            "value": "What the watch is measuring"
          }
        ]
      },
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "The watch samples your heart rate throughout the day. The \"resting\" number you see is the lower edge of that day's range — usually pulled from sitting periods or overnight. It is not a single reading; it is a quiet baseline."
          }
        ]
      },
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "For most adults, that baseline lands between 60 and 100. Athletes and very fit people often sit lower, in the 40s or 50s, because a stronger heart pushes more blood per beat and needs fewer beats to do the same work."
          }
        ]
      },
      {
        "type": "heading",
        "depth": 2,
        "children": [
          {
            "type": "text",
            "value": "What moves it over time"
          }
        ]
      },
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "Some things raise your resting heart rate, sometimes for hours, sometimes for years:"
          }
        ]
      },
      {
        "type": "list",
        "ordered": false,
        "items": [
          [
            {
              "type": "text",
              "value": "Caffeine and stimulants (short term)"
            }
          ],
          [
            {
              "type": "text",
              "value": "Stress, illness, fever, dehydration (short term)"
            }
          ],
          [
            {
              "type": "text",
              "value": "Certain prescribed medications (your doctor will know which)"
            }
          ],
          [
            {
              "type": "text",
              "value": "Loss of fitness over months"
            }
          ],
          [
            {
              "type": "text",
              "value": "Age, slowly, across decades"
            }
          ]
        ]
      },
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "Other things tend to lower it:"
          }
        ]
      },
      {
        "type": "list",
        "ordered": false,
        "items": [
          [
            {
              "type": "text",
              "value": "Consistent moderate movement, over weeks"
            }
          ],
          [
            {
              "type": "text",
              "value": "Better sleep, over weeks"
            }
          ],
          [
            {
              "type": "text",
              "value": "Recovery from an illness"
            }
          ]
        ]
      },
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "If your resting heart rate trends up by ten beats over a few weeks without an obvious reason, it is worth a mention at your next visit."
          }
        ]
      },
      {
        "type": "heading",
        "depth": 2,
        "children": [
          {
            "type": "text",
            "value": "Heart rate and blood pressure are different stories"
          }
        ]
      },
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "A high heart rate does not mean high blood pressure. A heart rate in range does not mean blood pressure is in range. The two are linked — both rise during exercise, both can rise under stress — but they tell different stories about your body. Your watch shows both because each adds context the other does not."
          }
        ]
      },
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "Talk to your doctor about what is right for you."
          }
        ]
      }
    ],
    "sourcePath": "apps/mobile/src/learn/articles/hr-001.mdx"
  },
  {
    "frontmatter": {
      "id": "numbers-001",
      "title": "What is blood pressure?",
      "category": "NUMBERS",
      "audience": [
        "self_buyer",
        "caregiver"
      ],
      "mode_relevance": [
        "self",
        "caregiver",
        "hybrid"
      ],
      "reading_context": {
        "systolic_min": 0,
        "systolic_max": 999,
        "diastolic_min": 0,
        "diastolic_max": 999
      },
      "inline_explainer_priority": 1,
      "related_cards": [
        "numbers-002",
        "numbers-005",
        "numbers-008"
      ],
      "sources": [
        "AHA/ACC 2017 Hypertension Guideline (Whelton et al)",
        "WHO Global Report on Hypertension 2023"
      ],
      "last_reviewed": "2026-05-09",
      "reviewed_by": null,
      "clinical_review_required": true,
      "clinical_reviewed_at": null,
      "locale_status": {
        "en": "complete",
        "yo": "pending",
        "ig": "pending",
        "ha": "pending"
      }
    },
    "blocks": [
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "A reading like "
          },
          {
            "type": "reading",
            "systolic": 124,
            "diastolic": 79
          },
          {
            "type": "text",
            "value": " is two numbers — the pressure your blood is making against the inside of your arteries, taken at one moment."
          }
        ]
      },
      {
        "type": "heading",
        "depth": 2,
        "children": [
          {
            "type": "text",
            "value": "Two numbers, one reading"
          }
        ]
      },
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "The top number is "
          },
          {
            "type": "definition",
            "term": "systolic",
            "children": [
              {
                "type": "text",
                "value": "the pressure when your heart contracts and pushes blood out"
              }
            ]
          },
          {
            "type": "text",
            "value": ". The bottom is "
          },
          {
            "type": "definition",
            "term": "diastolic",
            "children": [
              {
                "type": "text",
                "value": "the pressure between beats, when the heart fills again"
              }
            ]
          },
          {
            "type": "text",
            "value": ". Both are measured in mmHg — millimetres of mercury, a leftover unit from old glass-tube cuffs that the medical world never replaced."
          }
        ]
      },
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "Both numbers matter. A reading is in the higher range if either number is high."
          }
        ]
      },
      {
        "type": "heading",
        "depth": 2,
        "children": [
          {
            "type": "text",
            "value": "What \"in range\" looks like"
          }
        ]
      },
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "The AHA and ACC, who set the most-followed guideline in the United States, call below 120/80 mmHg the in-range mark for adults. Above that, readings step up through tiers — elevated, then Stage 1, then Stage 2. Other guidelines, including the European ones and NICE in the UK, draw the line at 140/90 instead. Your doctor will use whichever the practice follows."
          }
        ]
      },
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "A reading is a snapshot. One reading does not define you, and the watch on your wrist has not made a clinical judgement about your health."
          }
        ]
      },
      {
        "type": "heading",
        "depth": 2,
        "children": [
          {
            "type": "text",
            "value": "One reading, many causes"
          }
        ]
      },
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "Blood pressure shifts through the day. A 20 mmHg swing in the top number across a single day is common. Things that nudge it up or down:"
          }
        ]
      },
      {
        "type": "list",
        "ordered": false,
        "items": [
          [
            {
              "type": "text",
              "value": "Food, especially salty meals"
            }
          ],
          [
            {
              "type": "text",
              "value": "Sleep — short or restless sleep often raises morning numbers"
            }
          ],
          [
            {
              "type": "text",
              "value": "Caffeine, sometimes for an hour or two"
            }
          ],
          [
            {
              "type": "text",
              "value": "Stress and conversation, even mild"
            }
          ],
          [
            {
              "type": "text",
              "value": "A full bladder, a cold cuff, sitting cross-legged"
            }
          ],
          [
            {
              "type": "text",
              "value": "Recent activity"
            }
          ]
        ]
      },
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "Two readings taken a minute apart can differ by 5–10 mmHg. The trend across days and weeks is more meaningful than any single number."
          }
        ]
      },
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "Talk to your doctor about what is right for you."
          }
        ]
      }
    ],
    "sourcePath": "apps/mobile/src/learn/articles/numbers-001.mdx"
  },
  {
    "frontmatter": {
      "id": "sleep-001",
      "title": "Sleep stages explained",
      "category": "SLEEP",
      "audience": [
        "self_buyer",
        "caregiver"
      ],
      "mode_relevance": [
        "self",
        "caregiver",
        "hybrid"
      ],
      "reading_context": {
        "systolic_min": 0,
        "systolic_max": 999,
        "diastolic_min": 0,
        "diastolic_max": 999
      },
      "inline_explainer_priority": 1,
      "related_cards": [
        "sleep-002",
        "sleep-003"
      ],
      "sources": [
        "AASM Sleep Architecture Reference",
        "Comparative studies — consumer wearable sleep tracking accuracy"
      ],
      "last_reviewed": "2026-05-09",
      "reviewed_by": null,
      "clinical_review_required": false,
      "clinical_reviewed_at": null,
      "locale_status": {
        "en": "complete",
        "yo": "pending",
        "ig": "pending",
        "ha": "pending"
      }
    },
    "blocks": [
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "Your watch estimates how you slept by watching your movement and heart rate through the night. It separates the night into four phases — awake, light, deep, and REM — and gives you a rough breakdown of how much time you spent in each."
          }
        ]
      },
      {
        "type": "heading",
        "depth": 2,
        "children": [
          {
            "type": "text",
            "value": "The four phases"
          }
        ]
      },
      {
        "type": "paragraph",
        "children": [
          {
            "type": "strong",
            "children": [
              {
                "type": "text",
                "value": "Awake"
              }
            ]
          },
          {
            "type": "text",
            "value": " is exactly that — moments when you stirred, rolled, or briefly woke. A few short awake periods every night is part of how most adults sleep."
          }
        ]
      },
      {
        "type": "paragraph",
        "children": [
          {
            "type": "strong",
            "children": [
              {
                "type": "text",
                "value": "Light"
              }
            ]
          },
          {
            "type": "text",
            "value": " is most of your night. The body is still, the heart rate is low and steady, and you would wake easily from a small sound. Most adults spend about half their night here."
          }
        ]
      },
      {
        "type": "paragraph",
        "children": [
          {
            "type": "strong",
            "children": [
              {
                "type": "text",
                "value": "Deep"
              }
            ]
          },
          {
            "type": "text",
            "value": " is the heaviest sleep, often clustered earlier in the night. Heart rate drops further; movement is minimal. This is where the body does its slowest, deepest restoration work. Most adults get fifteen to twenty percent of their night here, and that share decreases gradually with age."
          }
        ]
      },
      {
        "type": "paragraph",
        "children": [
          {
            "type": "strong",
            "children": [
              {
                "type": "text",
                "value": "REM"
              }
            ]
          },
          {
            "type": "text",
            "value": " is when most dreaming happens. Heart rate becomes variable, the eyes move under the lids, and longer REM stretches usually come in the second half of the night. About a fifth of a typical night."
          }
        ]
      },
      {
        "type": "heading",
        "depth": 2,
        "children": [
          {
            "type": "text",
            "value": "Why this is an estimate"
          }
        ]
      },
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "The clinical version of sleep tracking is a polysomnography — sensors on the scalp, chest, and legs in a sleep lab. The watch does none of that. It uses heart-rate patterns and your movement to make an educated guess at the stages."
          }
        ]
      },
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "That guess is good enough for trends. It is not good enough to tell you anything about a sleep disorder. If you suspect you have one, your doctor has the right tests."
          }
        ]
      },
      {
        "type": "heading",
        "depth": 2,
        "children": [
          {
            "type": "text",
            "value": "What is worth watching"
          }
        ]
      },
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "Total time asleep is the most useful thing the watch tracks. Number of awake periods is a good trend over weeks. The exact deep-sleep percentage on a single night is not — it varies enough night-to-night that one number, in isolation, does not mean much."
          }
        ]
      },
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "Talk to your doctor about what is right for you."
          }
        ]
      }
    ],
    "sourcePath": "apps/mobile/src/learn/articles/sleep-001.mdx"
  },
  {
    "frontmatter": {
      "id": "spo2-001",
      "title": "What does blood oxygen mean?",
      "category": "SPO2",
      "audience": [
        "self_buyer",
        "caregiver"
      ],
      "mode_relevance": [
        "self",
        "caregiver",
        "hybrid"
      ],
      "reading_context": {
        "systolic_min": 0,
        "systolic_max": 999,
        "diastolic_min": 0,
        "diastolic_max": 999
      },
      "inline_explainer_priority": 1,
      "related_cards": [
        "spo2-002",
        "spo2-003"
      ],
      "sources": [
        "FDA Pulse Oximeter Accuracy and Limitations Guidance, 2023",
        "Comparative studies — wrist-worn SpO2 vs clinical pulse oximeters"
      ],
      "last_reviewed": "2026-05-09",
      "reviewed_by": null,
      "clinical_review_required": true,
      "clinical_reviewed_at": null,
      "locale_status": {
        "en": "complete",
        "yo": "pending",
        "ig": "pending",
        "ha": "pending"
      }
    },
    "blocks": [
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "SpO2 is a number that estimates how much oxygen is being carried in your blood, shown as a percentage. Most healthy adults read between 95 and 100%."
          }
        ]
      },
      {
        "type": "heading",
        "depth": 2,
        "children": [
          {
            "type": "text",
            "value": "What the number is telling you"
          }
        ]
      },
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "Your blood carries oxygen from your lungs to the rest of your body. "
          },
          {
            "type": "definition",
            "term": "SpO2",
            "children": [
              {
                "type": "text",
                "value": "\"S-P-O-2\" — the percentage of oxygen-carrying spots on your red blood cells that are filled"
              }
            ]
          },
          {
            "type": "text",
            "value": ". Higher is, generally, what the body wants."
          }
        ]
      },
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "Below 95%, the watch may be telling you one of two things: your blood oxygen is briefly lower than usual, or — more often — the sensor is not reading you well at that moment."
          }
        ]
      },
      {
        "type": "heading",
        "depth": 2,
        "children": [
          {
            "type": "text",
            "value": "What the watch can and cannot tell you"
          }
        ]
      },
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "The SpO2 reading on your watch is a wellness reference. It is not a clinical measurement. Wrist-worn sensors are less accurate than the pulse oximeters a doctor uses, and the watch is built to give you a sense of the trend, not a precise number."
          }
        ]
      },
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "Several things make a wrist sensor read low when blood oxygen is fine:"
          }
        ]
      },
      {
        "type": "list",
        "ordered": false,
        "items": [
          [
            {
              "type": "text",
              "value": "Cold hands or a tight band"
            }
          ],
          [
            {
              "type": "text",
              "value": "Tattoos or scars under the sensor"
            }
          ],
          [
            {
              "type": "text",
              "value": "Movement during the reading"
            }
          ],
          [
            {
              "type": "text",
              "value": "Darker skin tones — a known limitation of optical sensors"
            }
          ],
          [
            {
              "type": "text",
              "value": "A sensor that has slipped against the skin"
            }
          ]
        ]
      },
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "If you have a chronic respiratory condition such as asthma, COPD, or sleep apnea, do not rely on the watch SpO2 for any decision about your care. Use the device your doctor recommends."
          }
        ]
      },
      {
        "type": "heading",
        "depth": 2,
        "children": [
          {
            "type": "text",
            "value": "What is worth sharing"
          }
        ]
      },
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "A pattern of readings consistently in the low 90s across many days is worth mentioning at your next visit. A single low reading, especially with cold hands or after a busy moment, is common and usually means the sensor was not reading well."
          }
        ]
      },
      {
        "type": "paragraph",
        "children": [
          {
            "type": "text",
            "value": "Talk to your doctor about what is right for you."
          }
        ]
      }
    ],
    "sourcePath": "apps/mobile/src/learn/articles/spo2-001.mdx"
  }
] as const;

export const ARTICLES_BY_ID: Readonly<Record<string, CompiledArticle>> =
  ARTICLES.reduce<Record<string, CompiledArticle>>((acc, a) => {
    acc[a.frontmatter.id] = a;
    return acc;
  }, {});
